### ISSUE TITLE
Google  Account for login dialog:  Content citation errors

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct.net-website-bugs#188]
## Problem description

Issue1: 

The button of the Google account will refer to the style of the localized by default. Actually it shouldn't be there, just need to show the name like Facebook next to it.

Observed:
![Snipaste_2023-03-13_17-49-24](https://user-images.githubusercontent.com/45864744/224666661-f9587e57-d02c-4230-af6b-edbc52c7d1e8.png)

Expected:
![Snipaste_2023-03-13_17-58-26](https://user-images.githubusercontent.com/45864744/224671741-7c654c90-9849-40d2-8439-0fa89a1bba1d.png)

Issue2: 
In dark mode, if use the browser's save password, the background of the input box will appear in a harsh color. And The style of the Google account button is also not pretty.
![Snipaste_2023-03-13_17-48-04](https://user-images.githubusercontent.com/45864744/224670847-65816258-da9e-4f28-80bf-a66ceeaa08ad.png)

BTW, If possible, I recommend remove the text and only displaying the icon, which will be more concise.

**Comment by TomGullen** [comment]
I've fixed the CSS style for auto fill to make it look better for next release.

RE other points:
 - Google data-locale attribute is now set to en_US by default but this appears to have no affect on the rendered text
 - Google sign on limits style customisation options so has to stay as it is for now

**Comment by XHXIAIEIN** [comment]
In the r244 version, it still displays the localized text of the system language.
![Snipaste_2023-03-19_15-06-29](https://user-images.githubusercontent.com/45864744/226159938-9f22946f-67cd-43dc-9255-0b5389f8291b.png)


Expected: 
just display the `Google`

**Comment by TomGullen** [comment]
As I mentioned in my previous comment, I have set the data-locale attribute to en_US for the button which should force it to show just "Google", but this functionality appears to be broken and has no effect.  There's not a whole lot I can do about this until that bug is fixed.

**Comment by XHXIAIEIN** [comment]
@TomGullen I am requesting another investigation into this issue as it still exists. And it only happens with Constrct.

![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/fdc8b544-e204-4f70-8434-2fd86b68e55f)

I investigated the login interfaces of several other websites and none of them had this problem.

https://developers.google.com/identity/sign-in/web/build-button
![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/323d2707-ab02-4495-9efb-1794cdda9511)

![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/6e8f95c6-d742-4f63-90d0-da0e1c82eece)


https://stackoverflow.com/users/signup
![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/5629da1e-467c-471c-9b8b-f4bd383471f0)

https://slack.com/get-started#/createnew
![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/d3463dd2-4a10-4f66-aacb-f7924143550a)

https://www.reddit.com/
![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/c5868ded-523d-4e8b-83b5-2a2244790adb)

https://medium.com/
![image](https://github.com/Scirra/Construct.net-website-bugs/assets/45864744/9de1d523-73d7-4102-8772-510a331b23dd)
